function CV_max = cv_from_islr_threshold(islr_max, params)
% CV_FROM_ISLR_THRESHOLD  Exact inverse of the paper's ISLR--CV mapping.
%
% The direct ISLR constraint is equivalent to CV <= CV_max when the ISLR
% threshold is generated by direct_thresholds_from_cv(..., false).

if ~isfinite(islr_max)
    CV_max = Inf;
    return;
end

N = params.N;
kappa = params.kappa;

A = N * (2*kappa - 1) - 2*(kappa - 1);
B = (N - 1) * (N + 2*kappa - 2);
C = N + kappa - 1;
D = kappa - 1;

denom = 2*islr_max*D - A;
if abs(denom) < 1e-12
    error('ISLR threshold %.6g is too close to the non-invertible limit.', islr_max);
end

CV2 = (B - 2*islr_max*C) / denom;
CV_max = sqrt(max(real(CV2), 0));

end
